/*a
Pesquise os itens que foram vendidos sem desconto. As colunas presentes no resultado da consulta são: ID_NF, ID_ITEM, COD_PROD E VALOR_UNIT.*/
SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT
FROM questao1
WHERE DESCONTO IS NULL;

/*b
Pesquise os itens que foram vendidos com desconto. As colunas presentes no resultado da consulta são: ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT E O VALOR VENDIDO.OBS: O valor vendido é igual ao VALOR_UNIT - (VALOR_UNIT*(DESCONTO/100)).*/
SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, VALOR_UNIT - (VALOR_UNIT*(DESCONTO/100)) AS VALOR_VENDIDO
FROM questao1
WHERE DESCONTO IS NOT NULL;

/*c*/
/*UPTADE questao1
SET DESCONTO = 0 
WHERE DESCONTO IS NULL*/

/*d*/
SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, (QUANTIDADE * VALOR_UNIT) AS VALOR_TOTAL, DESCONTO, (VALOR_UNIT-(VALOR_UNIT*(DESCONTO/100))) AS VALOR_VENDIDO 
FROM questao1
WHERE QUANTIDADE IS NOT NULL;

/*e*/
SELECT ID_NF, SUM(QUANTIDADE * VALOR_UNIT) AS VALOR_TOTAL
FROM questao1
GROUP BY ID_NF
ORDER BY VALOR_TOTAL DESC;

/*f*/
SELECT ID_NF, VALOR_UNIT - (VALOR_UNIT*(DESCONTO/100)) AS VALOR_TOTAL
FROM questao1
GROUP BY ID_NF
ORDER BY VALOR_TOTAL DESC;

/*g*/
SELECT COD_PROD, SUM(QUANTIDADE) AS QUANTIDADE
FROM questao1
GROUP BY COD_PROD
ORDER BY QUANTIDADE DESC
LIMIT 1;

/*h*/
SELECT ID_NF, COD_PROD, QUANTIDADE
FROM questao1
WHERE QUANTIDADE > 10;

/*i*/
SELECT ID_NF, SUM(QUANTIDADE*VALOR_UNIT) AS QUANTIDADE
FROM questao1
GROUP BY ID_NF
HAVING QUANTIDADE > 500
ORDER BY QUANTIDADE DESC;

/*j*/
SELECT COD_PROD, AVG(DESCONTO) AS MEDIA
FROM questao1
GROUP BY COD_PROD;

/*k*/
SELECT COD PROD, MIN(DESCONTO) AS MENOR, MAX(DESCONTO) AS MAIOR, AVG(DESCONTO) AS MEDIA
FROM questao1
GROUP BY COD_PROD;

/*l*/
SELECT ID_NF, COUNT(QUANTIDADE) AS QUANTIDADE
FROM questao1
GROUP BY ID_NF
HAVING QUANTIDADE>3;